package mestok1.Telas._Produto;

import Utils.StrUtils;
import static Utils.StrUtils.RetiraCaracteresEspeciais;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import mestok1.Database.Entidade.Categoria;
import mestok1.Database.Entidade.Produto;
import mestok1.Database.Repository.CategoriaRepository;
import mestok1.Database.Repository.ProdutoRepository;
import mestok1.Database.Repository.SistemaRepository;

public class ProdutoForm extends javax.swing.JPanel {
    
    CategoriaRepository rep_categoria = new CategoriaRepository();
    ProdutoRepository rep_produto = new ProdutoRepository();
    
    public ProdutoForm() {
        initComponents();
        CarregaCategorias();
        AtualizaCheckBoxCategoria();
        StrUtils.limitarCaracteres(jTextField1, 20);
    }
    
    public void AtualizaCheckBoxCategoria(){
        checkbox_categoria.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String selecionado = (String) checkbox_categoria.getSelectedItem();
                    //System.out.println("Selecionado: " + selecionado);
                    PreencheTabelaComProdutos(selecionado);
                }
            });
    }
    
    public void CarregaCategorias(){
        ArrayList<Categoria> categorias = rep_categoria.GetCategoria(SistemaRepository.sistemaId);
        
        if (categorias.isEmpty()) {
            return;
        }

        for (Categoria categoria : categorias) {
            checkbox_categoria.addItem(categoria.getCategoriaNome());
        }

        PreencheTabelaComProdutos(categorias.get(0).getCategoriaNome());
    }
    
    public void PreencheTabelaComProdutos(String categoriaNome){
        Categoria categoria = rep_categoria.GetCategoriaPorNome(categoriaNome, SistemaRepository.sistemaId, Boolean.TRUE);
        ArrayList<Produto> produtos = rep_produto.GetProdutosPorCategoria(categoria.getCagegoriaId());
                        
        DefaultTableModel model = (DefaultTableModel) tb_produto.getModel();
        model.setRowCount(0);
        
        int comprimentoLista = produtos.size();

        if (comprimentoLista == 0) {
            return;
        }
        
        for (int i = 0; i <= (comprimentoLista-1); i++) {
            String content = produtos.get(i).getProdutoNome();
            int idContent = produtos.get(i).getProdutoId();
            model.addRow(new Object[] { idContent, content });
        }
    }
    
    public Boolean ValidaProdutoNome(String produto){
        if (produto.trim().isEmpty()) {
            return false;
        }
        else if (produto.length() <= 3) {
            return false;
        }
        else if(produto.length() > 20){
            JOptionPane.showMessageDialog(null, "Para cadastrar um produto, utilize de três (3) a vinte (20) caracteres!");
            return false;
        }
        
        return true;  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbox_categoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_produto = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(400, 400));

        checkbox_categoria.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                checkbox_categoriaCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jLabel1.setText("PRODUTO");

        tb_produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "QTD Estoque", "QTD Total", "QTD Pedido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_produto);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("Digite o nome do produto e pressione a tecla [ENTER]");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkbox_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jTextField1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(checkbox_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == 10) {
            String valorCategoria = "";
            String produto = jTextField1.getText();
            
            if (ValidaProdutoNome(produto.trim()) == false) {
                JOptionPane.showMessageDialog(null, "Digite um nome válido para prosseguir com o cadastro!");
                return;
            }
            
            int resposta = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente cadastrar este produto?",
                "Confirmação",
                JOptionPane.OK_CANCEL_OPTION
            );

            if (resposta == JOptionPane.OK_OPTION) {
                produto = RetiraCaracteresEspeciais(produto).toUpperCase();
                int selected = checkbox_categoria.getSelectedIndex();
                valorCategoria = checkbox_categoria.getItemAt(selected);
                
                Categoria categoria = rep_categoria.GetCategoriaPorNome(valorCategoria, SistemaRepository.sistemaId, true);
                
                Produto _produto = rep_produto.GetProdutoPorNome(produto, categoria.getCagegoriaId());
                
                if (_produto != null) {
                    JOptionPane.showMessageDialog(null, "o produto que você digitou já está cadastrado!");
                    PreencheTabelaComProdutos(categoria.getCategoriaNome());
                    jTextField1.setText(null);
                    return;
                }
                
                
                rep_produto.PostProduto(produto, valorCategoria);
            }
            
            PreencheTabelaComProdutos(valorCategoria);   
        }
        
        jTextField1.setText(null);
    }//GEN-LAST:event_jTextField1KeyPressed

    private void checkbox_categoriaCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_checkbox_categoriaCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_checkbox_categoriaCaretPositionChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> checkbox_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tb_produto;
    // End of variables declaration//GEN-END:variables
}
