/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mestok1.Telas._Estoque;

import Utils.DecUtils;
import Utils.StrUtils;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.System.out;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mestok1.Database.Entidade.Categoria;
import mestok1.Database.Entidade.Estoque;
import mestok1.Database.Entidade.Produto;
import mestok1.Database.Repository.CategoriaRepository;
import mestok1.Database.Repository.EstoqueRepository;
import mestok1.Database.Repository.ProdutoRepository;
import mestok1.Database.Repository.SistemaRepository;

public class EstoqueForm extends javax.swing.JPanel {
    
    CategoriaRepository rep_categoria = new CategoriaRepository();
    ProdutoRepository rep_produto = new ProdutoRepository();
    EstoqueRepository rep_estoque = new EstoqueRepository();

    public EstoqueForm() {
        initComponents();
        DecUtils.Listener(valor_contabil);
        StrUtils.limitarCaracteres(estoque_nome, 20);
        CarregaCategorias();
        AtualizaCheckBoxPorCategoria();
        
        if (checkbox_categoria.getItemCount() > 0) {
            PreencheTabelaComEstoqueDeProduto(checkbox_categoria.getItemAt(0).toString(), checkbox_produto.getItemAt(0).toString());
        }
    }
    
    public void PreencheTabelaComEstoqueDeProduto(String categoriaNome, String produtoNome){
        Produto produto = rep_produto.GetProdutoPorNome(produtoNome, 
                rep_categoria.GetCategoriaPorNome(categoriaNome, SistemaRepository.sistemaId, Boolean.TRUE).getCagegoriaId());
        
        DefaultTableModel model = (DefaultTableModel) tb_estoque.getModel();
        model.setRowCount(0);
        
        if (produto != null) {
            ArrayList<Estoque> estoque_lista = rep_estoque.GetEstoquesDoProduto(produto.getProdutoId());
            
            if (estoque_lista.isEmpty()) {
                return;
            }
            
            int comprimento_lista = estoque_lista.size();
            

            
            for (int i = 0; i <= (comprimento_lista-1); i++) {
                int id = estoque_lista.get(i).getId();
                String nome = estoque_lista.get(i).getNome();
                float valor = estoque_lista.get(i).getValorContabil();
                model.addRow(new Object[] { id, nome, valor });
            }
        }
    }
    
    public void AtualizaCheckBoxPorCategoria(){
        checkbox_categoria.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String selecionado = (String) checkbox_categoria.getSelectedItem();
                    Categoria categoria = rep_categoria.GetCategoriaPorNome(selecionado, SistemaRepository.sistemaId, Boolean.TRUE);
                    CarregaProdutos(categoria.getCagegoriaId());
                }
            });
    }
    
    public void CarregaCategorias(){
        ArrayList<Categoria> categorias = rep_categoria.GetCategoria(SistemaRepository.sistemaId);
        
        if (categorias.isEmpty()) {
            return;
        }

        for (Categoria categoria : categorias) {
            checkbox_categoria.addItem(categoria.getCategoriaNome());
        }
        
        checkbox_categoria.setSelectedIndex(0);
        
        CarregaProdutos(categorias.get(0).getCagegoriaId());
    }
    
    public void CarregaProdutos(int categoria){
        
        checkbox_produto.removeAllItems();
        
        ArrayList<Produto> produtos = rep_produto.GetProdutosPorCategoria(categoria);
        
        if (produtos.isEmpty()) {
            return;
        }

        for (Produto produto : produtos) {
            checkbox_produto.addItem(produto.getProdutoNome());
        }
        
        checkbox_produto.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_estoque = new javax.swing.JTable();
        estoque_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        estoque_qtd = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        valor_contabil = new javax.swing.JTextField();
        checkbox_categoria = new javax.swing.JComboBox<>();
        checkbox_produto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 400));

        jLabel1.setText("Valor");

        tb_estoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Valor unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_estoque);

        jLabel2.setText("Nome");

        jLabel3.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://img.icons8.com/?size=100&id=86265&format=png&color=000000")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel3.setToolTipText("Ir para tela de gráficos");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        estoque_qtd.setText("0");
        estoque_qtd.setEnabled(false);

        jLabel4.setText("QTD");

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cadastrar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        checkbox_categoria.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                checkbox_categoriaCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        checkbox_produto.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                checkbox_produtoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        checkbox_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_produtoActionPerformed(evt);
            }
        });

        jLabel5.setText("CATEGORIA");

        jLabel6.setText("PRODUTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(valor_contabil)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(estoque_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(estoque_nome))))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkbox_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkbox_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estoque_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(estoque_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(valor_contabil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jButton1))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkbox_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(checkbox_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void checkbox_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_produtoActionPerformed
        // TODO add your handling code here:
        PreencheTabelaComEstoqueDeProduto(checkbox_categoria.getSelectedItem().toString(),
                checkbox_produto.getSelectedItem().toString());
    }//GEN-LAST:event_checkbox_produtoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String categoria_selecionada = checkbox_categoria.getSelectedItem().toString();        
        String produto_selecionado = checkbox_produto.getSelectedItem().toString();
        String inserted_nome = estoque_nome.getText().trim();
        
        float[] valor = new float[1];
        Boolean valido = DecUtils.tryParseFloat(valor_contabil.getText(), valor);
        float valConvertido = valor[0];
        
        /*if (estoque_qtd.getText().isEmpty()) {
            return;
        }*/
        
        if (valido && valConvertido > 0 && valConvertido < 9999999) {
            
            int resposta = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente cadastrar este estoque para o produto " + produto_selecionado + " ?",
                "Confirmação",
                JOptionPane.OK_CANCEL_OPTION
            );
            
            if (resposta == JOptionPane.CANCEL_OPTION) {
                return;
            }
            
            //vazio
            if (produto_selecionado.isEmpty()) {
                return;
            }

            //menor que 3
            if (inserted_nome.length() < 3) {
                return;
            }

            inserted_nome = StrUtils.RetiraCaracteresEspeciais(inserted_nome);



            Produto produto = rep_produto.GetProdutoPorNome(
                        produto_selecionado, 
                        rep_categoria.GetCategoriaPorNome(categoria_selecionada, SistemaRepository.sistemaId, Boolean.TRUE
            ).getCagegoriaId());

            if (produto != null) {
                rep_estoque.PostEstoqueCategoria(produto.getProdutoId(), inserted_nome, valConvertido);
                PreencheTabelaComEstoqueDeProduto(categoria_selecionada, produto_selecionado);
            }    
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkbox_produtoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_checkbox_produtoCaretPositionChanged
        // TODO add your handling code here:
        PreencheTabelaComEstoqueDeProduto(checkbox_categoria.getSelectedItem().toString(),
                checkbox_produto.getSelectedItem().toString());

    }//GEN-LAST:event_checkbox_produtoCaretPositionChanged

    private void checkbox_categoriaCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_checkbox_categoriaCaretPositionChanged
        // TODO add your handling code here:
        
        Categoria categoria = rep_categoria.GetCategoriaPorNome(checkbox_categoria.getSelectedItem().toString(), 
                SistemaRepository.sistemaId, Boolean.TRUE);
        
        CarregaProdutos(categoria.getCagegoriaId());
        PreencheTabelaComEstoqueDeProduto(
                checkbox_categoria.getSelectedItem().toString(), 
                checkbox_produto.getSelectedItem().toString()
        );
    }//GEN-LAST:event_checkbox_categoriaCaretPositionChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> checkbox_categoria;
    private javax.swing.JComboBox<String> checkbox_produto;
    private javax.swing.JTextField estoque_nome;
    private javax.swing.JFormattedTextField estoque_qtd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_estoque;
    private javax.swing.JTextField valor_contabil;
    // End of variables declaration//GEN-END:variables
}
