package mestok1;

import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import mestok1.Database.Entidade.Sistema;
import mestok1.Database.Repository.SistemaRepository;
import mestok1.Telas.Menu.MenuBuilder;

public class MyPanelForm extends javax.swing.JPanel {

    /**
     * Creates new form MyPanelForm
     */
    SistemaRepository sistemaRepository;
    
    public MyPanelForm() {
        initComponents();
        sistemaRepository = new SistemaRepository();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c_codigo_sistema = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        c_codigo_sistema.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_codigo_sistema.setToolTipText("Obs: Caso o seu [código de sistema] não seja encontrado, será criado um novo sistema para o indentificador que foi inserido.");
        c_codigo_sistema.setName("c_codigo_sistema"); // NOI18N

        jLabel1.setText("Bem vindo ao MESTOK");

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ENTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(c_codigo_sistema, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_codigo_sistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        c_codigo_sistema.getAccessibleContext().setAccessibleDescription("Código do sistema. Obs: Caso o seu código não seja encontrado pelo sistema, será criado um novo registro para estoque.");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String input = c_codigo_sistema.getText();
        
        if (input != null && input.length() > 1) {
            sistemaRepository.identificador = input;
            
            Sistema sistema = sistemaRepository.GetSistema();
            
            if (sistema == null) {
                sistemaRepository.PostSistema();
                sistema = sistemaRepository.GetSistema();
            }
            
            JOptionPane.showMessageDialog(null, "SISTEMA INICIALIZADO, COD " + sistema.CodSistema);
            
            Window window = SwingUtilities.getWindowAncestor(this);
            if (window instanceof JFrame) {
                ((JFrame) window).dispose(); // Fecha o JFrame
            }
            
            var menu = new MenuBuilder();
            menu.codigoSistema = sistema.CodSistema;
            menu.Build();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_codigo_sistema;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
